Remove the document delete button from the documents index and the an…
performant-software/Annotation-Studio pull request #320
Opened 2020-10-15 12:24 UTC by timdunn22

## What does this PR do?
1. Removes delete button from documents index and anthologies index

## How to test?
1. Login and go to ____________ and see if there is a delete button on any of the documents tabs
2. Go to ___________ and see if when you search a document there is any delete button.

2020-10-15 17:10 UTC, jamiefolsom requested changes
The document index should have a delete button available, only for admins or document owners; the anthology show view (which has a document list on it), should NOT have a delete button; only a "remove from anthology" button, again, only for authorized users. @timdunn22

2020-10-15 18:41 UTC, jamiefolsom approved these changes

2020-10-15 18:41 UTC, jamiefolsom commented
👍 looks good to me, @timdunn22. please assign to @SteveMarvin for testing, and if he approves it, merge to master.

2020-10-15 18:42 UTC, jamiefolsom commented
@timdunn22 should be moved to review/qa as well as assigning to Steve.

2020-10-15 20:14 UTC, SteveMarvin commented
As a user, the anthology I am permitted to see does not provide me with a search bar.

My admin account will not log in. I get a redirect error: {"error":"redirect_uri_mismatch","error_description":"The redirect URI provided is missing or does not match","error_uri":"http:\/\/tools.ietf.org\/html\/rfc6749#section-3.1.2"}

2020-10-15 20:16 UTC, jamiefolsom commented
@SteveMarvin you have to use your email login, since OAuth depends on requests coming from a specific domain. Click log in >> log in with email. If you don't know your pw, there's a link there to reset it.

2020-10-28 18:13 UTC, jamiefolsom commented
@SteveMarvin ping me when you're available, and I will help you get in so we can get this approved and merged.

2020-10-30 18:54 UTC, merged