Rename Ryerson University to Toronto Metropolitan University
performant-software/Annotation-Studio pull request #412
Opened 2022-06-21 19:57 UTC by camdendotlol

# What this PR does

This PR renames all assets in preparation for the move from ryerson.covecollective.org to torontomu.covecollective.org due to the institution's name change.

## Notes

* The banner image prominently displays TMU's old name and logo. I imagine they would prefer to update the image, but that would be a self-contained change that we can do at any time during or after the migration process.
* I would also want to check with the tenant if they prefer torontomu.covecollective.org as the URL. I matched their official website, torontomu.ca, but it still seems a bit unwieldy.

## Database migration

This PR will remain a draft until we are ready to carry out the migration. There are a couple steps in the process that will have to be done either in the Rails CLI or in a Rake task.

My idea for this name change process is:

1. Put prod into maintenance mode. This is necessary because the Ryerson tenant will briefly be broken between the deployment of this PR and the database updates.
2. Merge and deploy this PR.
3. Rename the tenant and relevant config parameters in the COVE admin site.
4. Rename the tenant database from `ryerson` to `torontomu` as per these instructions: https://stackoverflow.com/a/34285885 As far as I can tell, this can only be done directly in Postgres, but maybe there is a way to handle it in the Rails CLI.
5. In the Rails CLI, switch to the `torontomu` tenant and update the list of users so `@ryerson.ca` is replaced with `@torontomu.ca` in all users' email addresses.
6. Take COVE out of maintenance mode.

Of course, there's plenty that can go wrong in this process, so I would want to test it on staging first.

2023-03-08 20:58 UTC, camdendotlol commented
Some more notes:

* a lot of users already have `@torontomu.ca` email addresses. I assume a find/replace for `@ryerson.edu` won't affect that.

2023-03-13 14:44 UTC, camdendotlol commented
# New plan

1. Run the email address migration stuff *first* (replace "@ryerson.ca" with "@torontomu.ca" in the users table as well as the Mongo database). There's no reason to do this simultaneously with the URL changes, so let's knock it out and make sure it completed successfully before moving to the next step. (Our contact confirmed that it's safe to do a simple string replacement on email addresses)
  1a. I remember seeing some variant email addresses such as "@english.ryerson.ca" but I couldn't spot them in the list today. After the main part of step 1, I would like to do a quick check for those and maybe manually update a few if they show up
2. Create a stub tenant at torontomu.covecollective.org and have the TMU people configure SAML setup for that domain. Once they've done that, remove the stub tenant and point the ryerson tenant to torontomu.covecollective.org
2 (alternative). If it's possible to point multiple domains to the same tenant, I could just add torontomu.covecollective.org to the ryerson tenant instead of creating a stub tenant

This plan should entirely prevent downtime, for TMU students and for COVE as a whole, but it might be safer to go into maintenance mode for step 1.

Once everything else is done, there should be a redirect from ryerson.covecollective.org to torontomu.covecollective.org. If that's not possible, we could at least use the `welcome_blurb` to tell users to switch to the new domain.

2023-03-13 18:37 UTC, jamiefolsom requested changes
Check the comment -- we don't want to break Ryerson before getting TMU set up.

2023-03-13 18:37 UTC, jamiefolsom commented on config/domain_specific/config.yml
>  ryerson.covecollective.org:
Looks like this will break Ryerson configuration before it sets up Toronto MU?

2023-03-13 18:46 UTC, merged